### ISSUE TITLE
[meta] Stanford Tidbit Caption Contest: Sept 5

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/beyond_the_paywall#27]
Tidbit Caption Contest
- [x] https://github.com/mozilla-rally/internal/issues/619
- [x] Test if the caption contest idea has any validity, on Twitter 
- [ ] If so, then create a wireframe for:
  - [ ] Rally hosted landing page
  - [ ] Rally will capture email addresses
  - [ ] Rally will capture tidbit captions
  - [ ] Suggestion was to build a "What's New" section on our site to keep users updated on what's happening w/Rally

**Comment by KennedyM-zillian** [comment]
Update: Working with Shoshana to prepare a proposal for SBS. We would like to test engagement with Twitter before committing our dev team to build a page.

**Comment by marniepw** [comment]
Closing. Decision: wasn't worth our time. Good learnings, though.
